### ISSUE TITLE
Expand the extension's coverage to Facebook links' parameters

### ISSUE THREAD

**Issue by secretdataz** [jakubboucek/kill-fbclid#2]
When you view a page's content, be it a link, photo, or video. There will be some long GET parameters in the URL. For example, \_\_xts\_\_ and \_\_tn\_\_ parameter.
Example,
```
https://www..facebook.com/PageURL/posts/NumericPostID?__xts__[0]=68.ARAhhIV8bT9k0d0owJOnCAjEsTmzL2N4qUkUsw07SMuXl-r3X-yubT8NRzJ1ohTTKGExajI5xBVQ4fQDnPgtVZ7JiagYosHfVpa6n_cHoEqGBl0Y-ETxxdk-ebGhPBUN773plPG_0gUrCo8qtXCqp2-DhpoSM3Z-0kSoMWqVy7imchYaCFmunWbd2XsPVSiJSN4_iiu-IYavlwK9yZWcz9S2SmYAt9yXt5Blgq0BnZQAk2psI_Ge3UP79n6GqyxTXn5wRrSbQJPXQI_rTLbolZyOGQYSrc6s9ESGZF9RdufoCtARJH-6WgMOUaDxnzBrdZX4LmMjVO2KAx8pkSQV-N0&__tn__=H-R
```

I could submit a pull request for supporting removal of these parameters, but I'd like an approval from you first, since it is not in the project's initial scope of removing only fbclid parameter to link outside Facebook.
If not, I'll create a separate project.

**Comment by jakubboucek** [comment]
This plugin solves only non-FB pages which is linked **from** FB. Your idea should looks great, but it's out of their business.

Thanks for your offer.
