### ISSUE TITLE
New Tab shortcut(Ctrl) also redirects the "parent Tab"

### ISSUE THREAD

**Issue by mikosoby** [jakubboucek/kill-fbclid#3]
Hi, I am using the PLUS version of the extension. After I click on the link on Facebook using while holding the **Ctrl** button to open the website in the new Tab it opens it in the new tab and also redirects the "parent Tab" to that website.

This also occurs when you use the "Open in the New Tab" feature in the "right click menu".

**Comment by jakubboucek** [comment]
Yep, I know. But that's is limitations based on API in browser.

Is probably possible to create more invasive way, but that's can results to another unpredictable fails.

Sorry to hear it.

**Comment by mikosoby** [comment]
That's sad. Thanks anyway.

**Comment by Diesel1017** [comment]
Hi,
The simple version is good (thanks :)), but the Plus new tab (parent) redirect is very annoying.

This is the invasive way?
https://github.com/maepon/cutFbclid
https://chrome.google.com/webstore/detail/cut-fbclid/bdnimhieijbfkojpmgilnpkembbohkdn

**Comment by shanness** [comment]
Damn!  I was wondering what was doing this.  Keeps losing the post I was opening the link from with no way back..  I'll subscribe in case there is some way to fix it..  How about a right click option where the extension integrates with the context menu and lets me open a new tab with the fbclid crap stripped out, and a way to turn off it stuffing up the parent tab if I ctrl click or right click / open in new tab?

**Comment by jakubboucek** [comment]
Currently version PLUS of extensions is now removed from store, because is unfixable. Please use [basic version of plugin](https://chrome.google.com/webstore/detail/kill-fbclid/jlmdkcaiejonohbmkgickmkgbpceokmn).

**Comment by damnms** [comment]
Thats sad, then this whole plugin makes no sense to me. If it passes the parameter to the destination page, "they" won. They can track whatever they want. Its useless to remove the parameter after the request has been done. At least for me.

**Comment by shanness** [comment]
Seems it's handled properly here
https://www.fbpurity.com/news/fb-purity-v26-0-is-out-now-lets-you-view-videos-in-the-newsfeed-without-video-ads/
```
New Automatically strips out “?fbclid” tracking parameter that facebook wrong headedly adds to external links
```

Installed and opened a bunch of external links, and none had fbclid :)
https://chrome.google.com/webstore/detail/fbfluffbustingpurity/nmkinhboiljjkhaknpaeaicmdjhagpep?hl=en
