### ISSUE TITLE
Please change your icon

### ISSUE THREAD

**Issue by mgziminsky** [jakubboucek/kill-fbclid#4]
It appears that you have taken your icon directly from my extension, https://github.com/mgziminsky/FacebookTrackingRemoval, and just mirrored it. 

My extension, and all it's assets are licensed under the GPLv3. You are free to use and modify my icon so long as you adhere to my license. That means you must license your version of the icon under the GPLv3, state any changes made, and include the GPLv3 license/copyright notice somewhere in your project.

Also, if you wish to use a derivative of my icon as your main extension icon, I ask that you make it easily distinguishable from my own, just mirroring is not enough. It should be different enough so not to be accidentally confused for my own extension.

If you would like, I can send you the source svg file for my icon so that you can more easily make changes. It was made using [Inkscape](https://inkscape.org/), in case you needed somewhere to start. If I do provide you a copy of the svg, you must also be willing to either publish the modified version in your project, or share it with anybody that requests it.

Thanks

**Comment by jakubboucek** [comment]
Hi Michael,
I am so sorry for this my big mistake. Picture is changed now.

I used picture from free image bank, I checked it was 100 % free, but not distinguish licence detail, or any author's wishes.

**Comment by mgziminsky** [comment]
Thank you for changing that.

Do you happen to remember where you found the image originally? I'd like to confirm it is being shared correctly since I haven't posted it anywhere myself.
