### ISSUE TITLE
Confusing name and description

### ISSUE THREAD

**Issue by urza** [jakubboucek/kill-fbclid#7]
If I understand correctly this extension only hides/removes the fbclid param from page URL bar, AFTER the link is clicked nad page is loaded. It means the tracking is still happening. This is not made clear in description in chrome store. Please consider making the description more clear to help users better understand what this extension does or doesn't do. Specifically it doesn't remove the tracking parameter from facebook links on facebook page to prevent the tracking.

**Comment by jakubboucek** [comment]
This extension is only for clean site for next usage (add to bookmark, copy & share, etc.

It's not preventing from tracking. 

These privacy feature was designed in [`plus variant`](https://github.com/jakubboucek/kill-fbclid/tree/plus) of plugin, bit it's deprecated now.

Did you see still confusing name or description anywhere?
