### ISSUE TITLE
Can this repo be used to remove search highlight?

### ISSUE THREAD

**Issue by DableUTeeF** [jakubboucek/kill-fbclid#9]
I noticed that Google's search highlight work by adding `#:~:text=` after the url.

By removing `#:~:text=` and everything after that effectively remove the highlight.

I tried
```
const param = ':text';
if (location.search.indexOf(param + '=') !== -1) {
    const url = new URL(location.href);
    url.searchParams.delete(param);
    history.replaceState(null, '', url.href);
}
```
But it doesn't work.

**Comment by jakubboucek** [comment]
This is off-topic to context exptensions scope.

In other way, `#:~:text=` is not member of `url.searchParams` or `url.search`, but it's `hash` part, see more at: https://developer.mozilla.org/en-US/docs/Web/API/URL/hash
